# Generated by Django 4.2.4 on 2023-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_log_id_alter_log_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
