# Generated by Django 4.2.4 on 2023-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_student_time_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_spend',
            field=models.IntegerField(default=0),
        ),
    ]
